name: Create release-tag intent
description: Create .github/release-tag.yml if missing and set outputs describing the chosen tag.
outputs:
  intent_created:
    description: Whether the intent file was created in this run.
    value: ${{ steps.intent.outputs.intent_created }}
  intent_modified:
    description: Whether the intent file was created or updated in this run.
    value: ${{ steps.intent.outputs.intent_modified }}
  intent_file:
    description: Path to the intent file.
    value: ${{ steps.intent.outputs.intent_file }}
  intent_tag:
    description: Tag value read or selected.
    value: ${{ steps.intent.outputs.intent_tag }}
  intent_tag_exists:
    description: Whether the selected tag already exists.
    value: ${{ steps.intent.outputs.intent_tag_exists }}
runs:
  using: composite
  steps:
    -
      name: Create intent
      id: intent
      shell: bash
      run: |
        set -euo pipefail
        INTENT_FILE=".github/release-tag.yml"
        compute_base_tag() {
          local t
          t=$(git describe --tags --abbrev=0 2>/dev/null || true)
          if [ -z "${t}" ]; then
            t="xpv0.0.0"
          fi
          printf '%s' "${t}"
        }
        bump_xpv_tag() {
          local base_tag version prefix digits width next_num padded
          base_tag="$1"
          version="${base_tag#xpv}"
          if [[ ! "${version}" =~ [0-9]+$ ]]; then
            printf '%s' "${base_tag}"
            return 0
          fi
          prefix="${version%[0-9]*}"
          digits="${version##*[^0-9]}"
          width=${#digits}
          next_num=$((10#${digits} + 1))
          padded=$(printf "%0${width}d" "${next_num}")
          printf 'xpv%s%s' "${prefix}" "${padded}"
        }
        compute_next_tag() {
          local base_tag version
          base_tag="$1"
          if [[ "${base_tag}" == xpv* ]]; then
            bump_xpv_tag "${base_tag}"
            return 0
          fi
          version="${base_tag}"
          if [[ "${version}" == v* ]]; then
            version="${version#v}"
          fi
          printf 'xpv%s.1' "${version}"
        }
        if [ -f "${INTENT_FILE}" ]; then
          FILE_TAG=$(grep -E '^tag:' "${INTENT_FILE}" | head -1 | sed -E 's/^tag:[[:space:]]*//')
          FILE_TAG=$(printf '%s' "${FILE_TAG}" | tr -d '\r' | xargs)
          BASE_TAG=$(compute_base_tag)
          if [ "${FILE_TAG}" = "${BASE_TAG}" ]; then
            NEXT_TAG=$(compute_next_tag "${BASE_TAG}")
            BASE_VERSION="${NEXT_TAG#xpv}"
            {
              echo "tag: ${NEXT_TAG}"
              echo "message: \"xpro version ${BASE_VERSION} tag\""
            } > "${INTENT_FILE}"
            git add "${INTENT_FILE}"
            BASE_TAG="${NEXT_TAG}"
            echo "intent_modified=true" >> "$GITHUB_OUTPUT"
          else
            echo "Intent tag does not match git base tag; leaving intent file unchanged. intent_tag=${FILE_TAG} git_base_tag=${BASE_TAG}"
            BASE_TAG="${FILE_TAG}"
            echo "intent_modified=false" >> "$GITHUB_OUTPUT"
          fi
          echo "intent_created=false" >> "$GITHUB_OUTPUT"
        else
          mkdir -p .github
          BASE_TAG=$(compute_base_tag)
          NEXT_TAG=$(compute_next_tag "${BASE_TAG}")
          BASE_VERSION="${NEXT_TAG#xpv}"
          {
            echo "tag: ${NEXT_TAG}"
            echo "message: \"xpro version ${BASE_VERSION} tag\""
          } > "${INTENT_FILE}"
          git add "${INTENT_FILE}"
          echo "intent_created=true" >> "$GITHUB_OUTPUT"
          echo "intent_modified=true" >> "$GITHUB_OUTPUT"
          BASE_TAG="${NEXT_TAG}"
        fi
        echo "intent_file=${INTENT_FILE}" >> "$GITHUB_OUTPUT"
        echo "intent_tag=${BASE_TAG}" >> "$GITHUB_OUTPUT"
        if [ -n "${BASE_TAG}" ] && git rev-parse -q --verify "refs/tags/${BASE_TAG}" >/dev/null 2>&1; then
          echo "intent_tag_exists=true" >> "$GITHUB_OUTPUT"
        else
          echo "intent_tag_exists=false" >> "$GITHUB_OUTPUT"
        fi
