name: Create release-tag intent
description: Create .github/release-tag.json if missing and set outputs describing the chosen tag.
outputs:
  intent_created:
    description: Whether the intent file was created in this run.
    value: ${{ steps.intent.outputs.intent_created }}
  intent_modified:
    description: Whether the intent file was created or updated in this run.
    value: ${{ steps.intent.outputs.intent_modified }}
  intent_file:
    description: Path to the intent file.
    value: ${{ steps.intent.outputs.intent_file }}
  intent_tag:
    description: Tag value read or selected.
    value: ${{ steps.intent.outputs.intent_tag }}
  intent_tag_exists:
    description: Whether the selected tag already exists.
    value: ${{ steps.intent.outputs.intent_tag_exists }}
runs:
  using: composite
  steps:
    -
      name: Create intent
      id: intent
      shell: bash
      run: |
        set -euo pipefail
        INTENT_FILE_JSON=".github/release-tag.json"
        INTENT_FILE_YML=".github/release-tag.yml"
        INTENT_MODIFIED=false
        INTENT_CREATED=false
        if [ -f "${INTENT_FILE_YML}" ]; then
          git rm -f "${INTENT_FILE_YML}"
          INTENT_MODIFIED=true
        fi
        compute_base_tag() {
          local t
          t=$(git describe --tags --abbrev=0 2>/dev/null || true)
          if [ -z "${t}" ]; then
            t="xpv0.0.0"
          fi
          printf '%s' "${t}"
        }
        bump_xpv_tag() {
          local base_tag version prefix digits width next_num padded
          base_tag="$1"
          version="${base_tag#xpv}"
          if [[ ! "${version}" =~ [0-9]+$ ]]; then
            printf '%s' "${base_tag}"
            return 0
          fi
          prefix="${version%[0-9]*}"
          digits="${version##*[^0-9]}"
          width=${#digits}
          next_num=$((10#${digits} + 1))
          padded=$(printf "%0${width}d" "${next_num}")
          printf 'xpv%s%s' "${prefix}" "${padded}"
        }
        compute_next_tag() {
          local base_tag version
          base_tag="$1"
          if [[ "${base_tag}" == xpv* ]]; then
            bump_xpv_tag "${base_tag}"
            return 0
          fi
          version="${base_tag}"
          if [[ "${version}" == v* ]]; then
            version="${version#v}"
          fi
          printf 'xpv%s.1' "${version}"
        }
        read_tag_from_json() {
          local p="$1"
          python3 -c 'import json,sys; print((json.load(open(sys.argv[1], "r", encoding="utf-8")).get("tag") or "").strip())' "$p"
        }
        if [ -f "${INTENT_FILE_JSON}" ]; then
          FILE_TAG=$(read_tag_from_json "${INTENT_FILE_JSON}")
          BASE_TAG=$(compute_base_tag)
          if [ "${FILE_TAG}" = "${BASE_TAG}" ]; then
            NEXT_TAG=$(compute_next_tag "${BASE_TAG}")
            BASE_VERSION="${NEXT_TAG#xpv}"
            python3 -c 'import json,sys; print(json.dumps({"tag": sys.argv[1], "message": sys.argv[2]}, indent=2, sort_keys=True))' "${NEXT_TAG}" "xpro version ${BASE_VERSION} tag" > "${INTENT_FILE_JSON}"
            git add "${INTENT_FILE_JSON}"
            BASE_TAG="${NEXT_TAG}"
            INTENT_MODIFIED=true
          else
            echo "Intent tag does not match git base tag; leaving intent file unchanged. intent_tag=${FILE_TAG} git_base_tag=${BASE_TAG}"
            BASE_TAG="${FILE_TAG}"
          fi
        else
          mkdir -p .github
          BASE_TAG=$(compute_base_tag)
          NEXT_TAG=$(compute_next_tag "${BASE_TAG}")
          BASE_VERSION="${NEXT_TAG#xpv}"
          python3 -c 'import json,sys; print(json.dumps({"tag": sys.argv[1], "message": sys.argv[2]}, indent=2, sort_keys=True))' "${NEXT_TAG}" "xpro version ${BASE_VERSION} tag" > "${INTENT_FILE_JSON}"
          git add "${INTENT_FILE_JSON}"
          INTENT_CREATED=true
          INTENT_MODIFIED=true
          BASE_TAG="${NEXT_TAG}"
        fi
        echo "intent_created=${INTENT_CREATED}" >> "$GITHUB_OUTPUT"
        echo "intent_modified=${INTENT_MODIFIED}" >> "$GITHUB_OUTPUT"
        echo "intent_file=${INTENT_FILE_JSON}" >> "$GITHUB_OUTPUT"
        echo "intent_tag=${BASE_TAG}" >> "$GITHUB_OUTPUT"
        if [ -n "${BASE_TAG}" ] && git rev-parse -q --verify "refs/tags/${BASE_TAG}" >/dev/null 2>&1; then
          echo "intent_tag_exists=true" >> "$GITHUB_OUTPUT"
        else
          echo "intent_tag_exists=false" >> "$GITHUB_OUTPUT"
        fi
