name: Create release-tag intent
description: Create .github/release-tag.yml if missing and set outputs describing the chosen tag.
outputs:
  intent_created:
    description: Whether the intent file was created in this run.
    value: ${{ steps.intent.outputs.intent_created }}
  intent_file:
    description: Path to the intent file.
    value: ${{ steps.intent.outputs.intent_file }}
  intent_tag:
    description: Tag value read or selected.
    value: ${{ steps.intent.outputs.intent_tag }}
  intent_tag_exists:
    description: Whether the selected tag already exists.
    value: ${{ steps.intent.outputs.intent_tag_exists }}
runs:
  using: composite
  steps:
    -
      name: Create intent
      id: intent
      shell: bash
      run: |
        set -euo pipefail
        INTENT_FILE=".github/release-tag.yml"
        if [ -f "${INTENT_FILE}" ]; then
          BASE_TAG=$(grep -E '^tag:' "${INTENT_FILE}" | head -1 | sed -E 's/^tag:[[:space:]]*//')
          BASE_TAG=$(printf '%s' "${BASE_TAG}" | tr -d '\r' | xargs)
          echo "intent_created=false" >> "$GITHUB_OUTPUT"
        else
          mkdir -p .github
          set +e
          BASE_TAG=$(git describe --tags --abbrev=0 --match 'xpv*' 2>/dev/null)
          RC=$?
          set -e
          if [ $RC -ne 0 ] || [ -z "${BASE_TAG}" ]; then
            set +e
            BASE_TAG=$(git describe --tags --abbrev=0 --match 'v*' 2>/dev/null)
            RC=$?
            set -e
          fi
          if [ $RC -ne 0 ] || [ -z "${BASE_TAG}" ]; then
            BASE_TAG=$(git describe --tags --abbrev=0 2>/dev/null || true)
          fi
          if [ -z "${BASE_TAG}" ]; then
            BASE_TAG="xpv0.0.0"
          fi
          BASE_VERSION="${BASE_TAG#xpv}"
          BASE_VERSION="${BASE_VERSION#v}"
          {
            echo "tag: ${BASE_TAG}"
            echo "message: \"xpro version ${BASE_VERSION} tag\""
          } > "${INTENT_FILE}"
          git add "${INTENT_FILE}"
          echo "intent_created=true" >> "$GITHUB_OUTPUT"
        fi
        echo "intent_file=${INTENT_FILE}" >> "$GITHUB_OUTPUT"
        echo "intent_tag=${BASE_TAG}" >> "$GITHUB_OUTPUT"
        if [ -n "${BASE_TAG}" ] && git rev-parse -q --verify "refs/tags/${BASE_TAG}" >/dev/null 2>&1; then
          echo "intent_tag_exists=true" >> "$GITHUB_OUTPUT"
        else
          echo "intent_tag_exists=false" >> "$GITHUB_OUTPUT"
        fi
