x-all: &all-alias
  environment:
    - DISPLAY=${DISPLAY_ENV}
    - XAUTHORITY=${XAUTH_ENV}
  user: ${USER}
  stdin_open: true
  tty: true
  working_dir: /bpvol/${COMPOSE_PROJECT_NAME}
x-bld: &bld-alias
  cap_add:
    - SYS_PTRACE
  volumes:
    - .:/bpvol/${COMPOSE_PROJECT_NAME}
    - ..:/bpvol/workspace
    - /tmp/.X11-unix:/tmp/.X11-unix
    - /var/run/docker.sock:/var/run/docker.sock
    - ~/.ssh:/home/${USER}/.ssh
    - ~/.gitconfig:/home/${USER}/.gitconfig
x-all-build-args: &all-build-args-alias
  BPROTAG: ${BPROTAG}
  USERNAME: ${USER}
  USERID: ${USERID}
  GROUPID: ${GROUPID}
  DOCKGID: ${DOCKGID}
  COPY_IT: ${COPY_IT}
  RUN_IT: ${RUN_IT}
  TZ: ${TZ}
x-bld-build-args: &bld-build-args-alias
  WEBPRO: ${WEBPRO}
  CRTOOL: ${CRTOOL}
services:
  bld:
    <<: [*all-alias, *bld-alias]
    build:
      context: .devcontainer
      dockerfile: rocky85-bld.dockerfile
      args:
        <<: [*all-build-args-alias, *bld-build-args-alias]
        ADDSRC1: ${ADDSRC1}
        ADDSRC2: ${ADDSRC2}
    hostname: ${HNAME}
    profiles:
      - pbld
