name: CMake Build
inputs:
  artifact-pattern:
    required: true
  cmake-workflow-preset:
    required: true
  cmake-preset:
    required: true
  no-install-preset:
    required: true
  name-suffix:
    required: false
    default: ""
runs:
  using: composite
  steps:
    -
      name: CMake Configure
      shell: bash
      run: cmake --preset=${{ inputs.cmake-preset }}
    -
      name: Upload CMake logs
      uses: actions/upload-artifact@v4
      with:
        name: cmake-logs-${{ inputs.cmake-preset }}-${{ runner.arch }}${{ inputs.name-suffix }}
        path: |
          _bld-${{ inputs.cmake-preset }}/CMakeFiles/CMakeConfigureLog.yaml
    -
      name: CMake Workflow
      shell: bash
      run: cmake --workflow --preset=${{ inputs.cmake-workflow-preset }}
    -
      name: Find package
      id: find_package
      if: ${{ inputs.cmake-workflow-preset != inputs.no-install-preset }}
      shell: bash
      run: |
        file=$(pwd)/$(ls _bld-${{ inputs.cmake-preset }}/${{ inputs.artifact-pattern }})
        if [[ ! -f "$file" ]]; then
          echo "::error::Package not found!" >&2
          exit 1
        fi
        echo "filepath=$file" >> $GITHUB_OUTPUT
        echo "filename=$(basename $file)" >> $GITHUB_OUTPUT
      working-directory: ${{ github.workspace }}
    -
      name: Find manifest
      id: find_manifest
      if: ${{ inputs.cmake-workflow-preset != inputs.no-install-preset }}
      shell: bash
      run: |
        build_dir=_bld-${{ inputs.cmake-preset }}
        file=$(find "$build_dir" -type f -name "${{ github.event.repository.name }}-*.manifest.cmake" | head -1)
        file=$(pwd)/$file
        if [[ ! -f "$file" ]]; then
          echo "::error::Manifest not found!" >&2
          ls -la "$build_dir" || true
          exit 1
        fi
        echo "filepath=$file" >> $GITHUB_OUTPUT
        echo "filename=$(basename $file)" >> $GITHUB_OUTPUT
      working-directory: ${{ github.workspace }}
    -
      name: Convert Git Bash paths to Windows paths
      id: convert_paths
      if: ${{ inputs.cmake-workflow-preset != inputs.no-install-preset && runner.os == 'Windows' }}
      shell: pwsh
      run: |
        $pkgWindowsPath = '${{ steps.find_package.outputs.filepath }}' -replace '^/([a-zA-Z])/', '$1:/' -replace '/', '\\'
        $manifestWindowsPath = '${{ steps.find_manifest.outputs.filepath }}' -replace '^/([a-zA-Z])/', '$1:/' -replace '/', '\\'
        echo "package_windows_path=$pkgWindowsPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        echo "manifest_windows_path=$manifestWindowsPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
    -
      name: Upload package artifact
      if: ${{ inputs.cmake-workflow-preset != inputs.no-install-preset }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.find_package.outputs.filename }}
        path: ${{ runner.os == 'Windows' && steps.convert_paths.outputs.package_windows_path || steps.find_package.outputs.filepath }}
    -
      name: Upload manifest artifact
      if: ${{ inputs.cmake-workflow-preset != inputs.no-install-preset }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.find_manifest.outputs.filename }}-${{ inputs.cmake-preset }}-${{ runner.arch }}${{ inputs.name-suffix }}
        path: ${{ runner.os == 'Windows' && steps.convert_paths.outputs.manifest_windows_path || steps.find_manifest.outputs.filepath }}
    -
      name: Check for dirty repo
      shell: bash
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "::error::Dirty repo detected!"
          git status
          echo "--- git diff --name-status"
          git --no-pager diff --name-status

          if git diff --name-only | grep -q "^include/wx/stc/stc.h$"; then
            echo "--- git diff -- include/wx/stc/stc.h"
            git --no-pager diff -- include/wx/stc/stc.h
          fi

          echo "--- python3 --version"
          python3 --version || true
          echo "--- locale"
          locale || true

          git submodule foreach git status
          exit 1
        fi
