name: CMake Build
description: Configure and build using CMake presets and upload build artifacts.
inputs:
  artifact-pattern:
    required: true
  cmake-workflow-preset:
    required: true
  cmake-preset:
    required: true
  no-install-preset:
    required: true
  name-suffix:
    required: false
    default: ""
  enable-tmate:
    required: false
    default: "false"
runs:
  using: composite
  steps:
    -
      name: CMake Configure
      shell: bash
      run: cmake --preset=${{ inputs.cmake-preset }}
    -
      name: Upload CMake logs
      uses: actions/upload-artifact@v4
      with:
        name: cmake-logs-${{ inputs.cmake-preset }}-${{ runner.arch }}${{ inputs.name-suffix }}
        path: |
          _bld-${{ inputs.cmake-preset }}/CMakeFiles/CMakeConfigureLog.yaml
    -
      name: CMake Workflow
      shell: bash
      id: cmake_workflow
      continue-on-error: true
      run: cmake --workflow --preset=${{ inputs.cmake-workflow-preset }}
    -
      name: Install tmate (on failure)
      if: ${{ inputs.enable-tmate == 'true' && steps.cmake_workflow.outcome == 'failure' }}
      shell: bash
      run: |
        if command -v tmate >/dev/null 2>&1; then
          exit 0
        fi
        if command -v dnf >/dev/null 2>&1; then
          sudo dnf -y install tmate openssh-clients || (sudo dnf -y install epel-release && sudo dnf -y install tmate openssh-clients)
        elif command -v yum >/dev/null 2>&1; then
          sudo yum -y install tmate openssh-clients || (sudo yum -y install epel-release && sudo yum -y install tmate openssh-clients)
        elif command -v apt-get >/dev/null 2>&1; then
          sudo apt-get update
          sudo apt-get install -y tmate openssh-client
        else
          echo "No supported package manager found to install tmate" >&2
          exit 1
        fi
    -
      name: Setup tmate session (on failure)
      if: ${{ inputs.enable-tmate == 'true' && steps.cmake_workflow.outcome == 'failure' }}
      uses: mxschmitt/action-tmate@v3
      with:
        install-dependencies: false
    -
      name: Fail if CMake Workflow failed
      if: ${{ steps.cmake_workflow.outcome == 'failure' }}
      shell: bash
      run: exit 1
    -
      name: Find package
      id: find_package
      if: ${{ inputs.cmake-workflow-preset != inputs.no-install-preset }}
      shell: bash
      run: |
        file=$(pwd)/$(ls _bld-${{ inputs.cmake-preset }}/${{ inputs.artifact-pattern }})
        if [[ ! -f "$file" ]]; then
          echo "::error::Package not found!" >&2
          exit 1
        fi
        echo "filepath=$file" >> $GITHUB_OUTPUT
        echo "filename=$(basename $file)" >> $GITHUB_OUTPUT
      working-directory: ${{ github.workspace }}
    -
      name: Find manifest
      id: find_manifest
      if: ${{ inputs.cmake-workflow-preset != inputs.no-install-preset }}
      shell: bash
      run: |
        build_dir=_bld-${{ inputs.cmake-preset }}
        file=$(find "$build_dir" -type f -name "${{ github.event.repository.name }}-*.manifest.cmake" | head -1)
        file=$(pwd)/$file
        if [[ ! -f "$file" ]]; then
          echo "::error::Manifest not found!" >&2
          ls -la "$build_dir" || true
          exit 1
        fi
        echo "filepath=$file" >> $GITHUB_OUTPUT
        echo "filename=$(basename $file)" >> $GITHUB_OUTPUT
      working-directory: ${{ github.workspace }}
    -
      name: Convert Git Bash paths to Windows paths
      id: convert_paths
      if: ${{ inputs.cmake-workflow-preset != inputs.no-install-preset && runner.os == 'Windows' }}
      shell: pwsh
      run: |
        $pkgWindowsPath = '${{ steps.find_package.outputs.filepath }}' -replace '^/([a-zA-Z])/', '$1:/' -replace '/', '\\'
        $manifestWindowsPath = '${{ steps.find_manifest.outputs.filepath }}' -replace '^/([a-zA-Z])/', '$1:/' -replace '/', '\\'
        echo "package_windows_path=$pkgWindowsPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        echo "manifest_windows_path=$manifestWindowsPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
    -
      name: Upload package artifact
      if: ${{ inputs.cmake-workflow-preset != inputs.no-install-preset }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.find_package.outputs.filename }}
        path: ${{ runner.os == 'Windows' && steps.convert_paths.outputs.package_windows_path || steps.find_package.outputs.filepath }}
    -
      name: Upload manifest artifact
      if: ${{ inputs.cmake-workflow-preset != inputs.no-install-preset }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.find_manifest.outputs.filename }}-${{ inputs.cmake-preset }}-${{ runner.arch }}${{ inputs.name-suffix }}
        path: ${{ runner.os == 'Windows' && steps.convert_paths.outputs.manifest_windows_path || steps.find_manifest.outputs.filepath }}
    -
      name: Check for dirty repo
      shell: bash
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "::error::Dirty repo detected!"
          git status
          echo "--- git diff --name-status"
          git --no-pager diff --name-status
          echo "--- git diff --stat"
          git --no-pager diff --stat
          echo "--- git diff"
          git --no-pager diff

          echo "--- submodule status"
          git submodule status --recursive || true
          git submodule foreach --recursive 'echo "--- submodule: $name"; git status; git --no-pager diff --name-status; git --no-pager diff || true'
          exit 1
        fi
