set(file CMakePresetsBase.json)
if(DEFINED binaryDir)
  if(EXISTS ${file})
    file(READ ${file} presetsBase)
    set(regex "^.*\"binaryDir\": \"(.*)\",?$")
    file(STRINGS ${file} var REGEX "${regex}")
    string(REGEX REPLACE "${regex}" "\\1" var ${var})
    string(REPLACE "${var}" "${binaryDir}" modPresetsBase "${presetsBase}")
    file(WRITE ${file} "${modPresetsBase}")
    if(NOT "${presetsBase}" STREQUAL "${modPresetsBase}")
      set(mod TRUE)
    endif()
  endif()
endif()
if(DEFINED ENV{JETPACK})
  set(presetName JetPack)
else()
  set(presetName ${CMAKE_HOST_SYSTEM_NAME})
endif()
execute_process(COMMAND ${CMAKE_COMMAND} --workflow --preset=${presetName})
if(mod)
  file(WRITE ${file} "${presetsBase}")
endif()
