function(generateSyncScript)
  set(options XP_MODULE)
  set(reqArgs PKG BRANCH REPO TAG SHA256_Linux SHA256_win64)
  set(oneValueArgs ${reqArgs} BASE DESC DIST_DIR LICENSE UPSTREAM VER WEB URL_Linux URL_win64 SHA256_utres)
  set(multiValueArgs DEPS EXE_DEPS)
  cmake_parse_arguments(P "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  foreach(arg ${reqArgs})
    if(NOT DEFINED P_${arg})
      message(FATAL_ERROR "generateSyncScript: ${P_PKG} missing required argument: ${arg}")
    endif()
  endforeach()
  execute_process(COMMAND ${CMAKE_COMMAND} -E echo '${P_REPO}' COMMAND cut -d/ -f2 OUTPUT_VARIABLE P_ORG OUTPUT_STRIP_TRAILING_WHITESPACE)
  if(DEFINED P_SHA256_utres)
    set(unitTestResults "\ndownloadAndCompare Unit_Test_Results.tar.xz ${P_SHA256_utres}")
  endif()
  configure_file(${CMAKE_CURRENT_LIST_DIR}/sync.sh.in Sync${P_PKG}.sh)
endfunction()
include(${CMAKE_CURRENT_LIST_DIR}/pros.cmake)
math(EXPR argIdx "${CMAKE_ARGC}-1")
foreach(n RANGE 4 ${argIdx}) # cmake[ARGV0] -P[ARGV1] path/to/sync.cmake[ARGV2] --[ARGV3]
  generateSyncScript(PKG ${CMAKE_ARGV${n}} ${xp_${CMAKE_ARGV${n}}})
endforeach()
