set(buildpro_REV 24.07)
if(NOT DEFINED externpro_REV)
  set(externpro_REV 24.04)
endif()
find_package(externpro REQUIRED)
include(xpfunmac)
if(webpro)
  set(webpro_REV 24.03)
  find_package(webpro REQUIRED)
  include(xpweb)
endif()
if(NOT DEFINED XP_SANITIZER)
  set(XP_SANITIZER "ASAN")
endif()
set(XP_COVERAGE ON)
set(XP_COVERAGE_RM '*/test/*' '*/tool/*')
xpSetFlags()
xpFindPkg(PKGS palam)
xpGenerateRevision() # Revision INTERFACE library, Revision.hpp
set(PACKAGE_VENDOR "Space Dynamics Lab")
set(XP_INSTALLDIR "VantageSuite/${CMAKE_PROJECT_NAME}")
set(GRAPHVIZ_EXTERNAL_LIBS FALSE)
set(GRAPHVIZ_GENERATE_PER_TARGET FALSE)
set(GRAPHVIZ_GENERATE_DEPENDERS FALSE)
set(GRAPHVIZ_IGNORE_TARGETS "(.*)Test$" "(.*)Version$")
if(NOT DEFINED cppCoverage)
  set(cppCoverage ON)
endif()
if(cppCoverage)
  list(APPEND langs CPP)
endif()
if(webpro)
  list(APPEND langs JS)
endif()
if(csharpCoverage)
  list(APPEND langs CSharp)
endif()
xpAddCoverage(${langs})
