name: xpBuild
permissions:
  contents: read
  pull-requests: write
on:
  push:
    tags: ["xpv*"]
  pull_request:
    branches: ["xpro"]
  workflow_dispatch:
jobs:
  linux:
    permissions:
      contents: read
      pull-requests: write
      packages: write
    uses: externpro/externpro/.github/workflows/build-linux.yml@25.07.9
    secrets: inherit
  macos:
    uses: externpro/externpro/.github/workflows/build-macos.yml@25.07.9
    secrets: inherit
  windows:
    uses: externpro/externpro/.github/workflows/build-windows.yml@25.07.9
    secrets: inherit
