name: Build
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:
jobs:
  linux:
    permissions:
      contents: read
      pull-requests: write
      packages: write
    uses: externpro/externpro/.github/workflows/build-linux.yml@25.06.6
    secrets: inherit
  macos:
    uses: externpro/externpro/.github/workflows/build-macos.yml@25.06.6
    secrets: inherit
  windows:
    uses: externpro/externpro/.github/workflows/build-windows.yml@25.06.6
    secrets: inherit
