name: Build
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:
jobs:
  linux:
    permissions:
      contents: read
      pull-requests: write
      packages: write
    uses: externpro/externpro/.github/workflows/build-linux.yml@main
    with:
      cmake-workflow-preset: Linux
    secrets: inherit
  macos:
    uses: externpro/externpro/.github/workflows/build-macos.yml@main
    with:
      cmake-workflow-preset: Darwin
    secrets: inherit
  windows:
    uses: externpro/externpro/.github/workflows/build-windows.yml@main
    with:
      cmake-workflow-preset: Windows
    secrets: inherit
