name: xpInit externpro
permissions:
  contents: write
  pull-requests: write
  packages: write
on:
  workflow_dispatch:
jobs:
  init:
    uses: externpro/externpro/.github/workflows/init-externpro.yml@main
    secrets:
      automation_token: ${{ secrets.XPRO_TOKEN }}
