name: xpRelease
on:
  workflow_dispatch:
    inputs:
      workflow_run_url:
        description: 'URL of the workflow run containing artifacts to upload (e.g., https://github.com/owner/repo/actions/runs/123456789)'
        required: true
        type: string
  workflow_run:
    workflows: ["xpBuild"]
    types: [completed]
jobs:
  dispatch-at-tag:
    if: >-
      github.event_name == 'workflow_run' &&
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_branch, 'xpv')
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      -
        name: Dispatch xpRelease at tag
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
          RUN_URL: ${{ github.event.workflow_run.html_url }}
          TAG_REF: ${{ github.event.workflow_run.head_branch }}
        run: |
          set -euo pipefail
          gh api -X POST "repos/${{ github.repository }}/actions/workflows/xprelease.yml/dispatches" \
            -f ref="$TAG_REF" \
            -f inputs[workflow_run_url]="$RUN_URL"
  # Upload build artifacts as release assets
  release-from-build:
    if: github.event_name == 'workflow_dispatch'
    uses: externpro/externpro/.github/workflows/release-from-build.yml@25.07.8
    with:
      workflow_run_url: ${{ github.event.inputs.workflow_run_url }}
    permissions:
      contents: write
      id-token: write
      attestations: write
    secrets: inherit
