name: xpUpdate externpro
permissions:
  contents: write
  pull-requests: write
  packages: read
on:
  workflow_dispatch:
jobs:
  update:
    uses: externpro/externpro/.github/workflows/update-externpro.yml@main
    secrets:
      automation_token: ${{ secrets.XPRO_TOKEN }}
