name: Create Release
on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create release for'
        required: true
        type: string
      create_release:
        description: 'Create release if it does not exist'
        required: false
        type: boolean
        default: true
      prerelease:
        description: 'Mark as prerelease'
        required: false
        type: boolean
        default: false

jobs:
  # Build for Linux
  build-linux:
    uses: ./.github/workflows/build-linux.yml
    with:
      email: ${{ github.actor }}@users.noreply.github.com
      runon: ubuntu-latest
      cmake-workflow-preset: LinuxRelease
    secrets: inherit

  # Build for Windows
  build-windows:
    uses: ./.github/workflows/build-windows.yml
    with:
      cmake-workflow-preset: WindowsRelease
    secrets: inherit

  # Upload artifacts as release assets
  upload-release-assets:
    needs: [build-linux, build-windows]
    if: always() && (needs.build-linux.result == 'success' || needs.build-windows.result == 'success')
    uses: ./.github/workflows/upload-release-assets.yml
    with:
      release_tag: ${{ github.event.inputs.tag || github.ref_name }}
      artifact_pattern: "*.tar.xz"
      create_release: ${{ github.event.inputs.create_release || true }}
      release_name: "Release ${{ github.event.inputs.tag || github.ref_name }}"
      release_body: |
        ## What's Changed
        
        This release includes builds for:
        - Linux (x64)
        - Windows (x64)
        
        ### Download
        - **Linux**: Download the `.tar.xz` file for Linux systems
        - **Windows**: Download the `.tar.xz` file for Windows systems
        
        Full Changelog: https://github.com/${{ github.repository }}/compare/v1.0.0...${{ github.event.inputs.tag || github.ref_name }}
      prerelease: ${{ github.event.inputs.prerelease || false }}
      draft: false
    secrets: inherit
