name: Create Release
on:
  workflow_dispatch:
    inputs:
      workflow_run_url:
        description: 'URL of the workflow run containing artifacts to upload (e.g., https://github.com/owner/repo/actions/runs/123456789)'
        required: true
        type: string
      draft:
        description: 'Mark as draft'
        required: false
        type: boolean
        default: false
jobs:
  # Upload artifacts as release assets
  upload-release-assets:
    uses: ./.github/workflows/upload-release-assets.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      workflow_run_url: ${{ github.event.inputs.workflow_run_url }}
      artifact_pattern: "*.tar.xz"
      release_body_template: |
        ## What's Changed
 
        This release includes build artifacts from workflow run:
        {workflow_run_url}

        ### Download
        - Download the appropriate `.tar.xz` file for your platform
 
        ### Verification
        SHA256 checksums are provided below for artifact verification.
      draft: ${{ github.event.inputs.draft }}
