name: Create Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create release for'
        required: true
        type: string
      workflow_run_url:
        description: 'URL of the workflow run containing artifacts to upload (e.g., https://github.com/owner/repo/actions/runs/123456789)'
        required: true
        type: string
      create_release:
        description: 'Create release if it does not exist'
        required: false
        type: boolean
        default: true
      prerelease:
        description: 'Mark as prerelease'
        required: false
        type: boolean
        default: false

jobs:
  # Upload artifacts as release assets
  upload-release-assets:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/upload-release-assets.yml
    with:
      release_tag: ${{ github.event.inputs.tag }}
      workflow_run_url: ${{ github.event.inputs.workflow_run_url }}
      artifact_pattern: "*.tar.xz"
      create_release: ${{ github.event.inputs.create_release }}
      release_name: "Release ${{ github.event.inputs.tag }}"
      release_body: |
        ## What's Changed
  
        This release includes build artifacts from workflow run:
        ${{ github.event.inputs.workflow_run_url }}

        ### Download
        - Download the appropriate `.tar.xz` file for your platform
 
        ### Verification
        SHA256 checksums are provided below for artifact verification.
 
        Full Changelog: https://github.com/${{ github.repository }}/compare/v1.0.0...${{ github.event.inputs.tag }}
      prerelease: ${{ github.event.inputs.prerelease }}
      draft: false
    secrets: inherit
